export enum ExercisePermission {
  PRIVATE = 'PRIVATE',
  PROTECTED = 'PROTECTED',
  PROTECTED_READ_ONLY = 'PROTECTED_READ_ONLY',
  PUBLIC = 'PUBLIC',
  PUBLIC_READ_ONLY = 'PUBLIC_READ_ONLY',
}

export enum Permission {
  ADMIN_READ = 'ADMIN_READ',
  ADMIN_EDIT = 'ADMIN_EDIT',
  USER_READ = 'USER_READ',
  USER_EDIT = 'USER_EDIT',
  ASSIGN_EXERCISE = 'ASSIGN_EXERCISE',
}

export enum Scope {
  CENTER = 'CENTER',
  ORGANIZATION = 'ORGANIZATION',
  ALL = 'ALL',
}
